version: '3'

services:
    api:
        build : Dockerfile
        conrainer_name: lineapi
        volumes:
            - ./src:/src/src
        ports:
            - 5000:5000
        environment:
            - TZ=Asia/Tokyo
            - lineapi=
            - url=
        command: "python src/main.py"
    db:
        image: postgres:14
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./db-store:/var/lib/postgresql/data
        environment:
            - TZ=Asia/Tokyo

volumes:
